packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - aws-sdk
  - bcrypt
  - core-js-pure
  - prisma
  - sharp
  - unrs-resolver
