export enum SettingComponentEnum {
  INPUT_TEXT = 'input-text',
  INPUT_NUMBER = 'input-number',
  INPUT_DURATION = 'input-duration',
  INPUT_BYTES = 'input-bytes',
  INPUT_SECRET = 'input-secret',
  INPUT_FILE = 'input-file',
  INPUT_TAGS = 'input-tags',
  COMBOBOX = 'combobox',
  RADIO = 'radio',
  COLOR_PICKER = 'color-picker',
  SWITCH = 'switch',
  CHECKBOX = 'checkbox',
  ENTITY_PICKER = 'entity-picker',
}