import { toPascalCase } from '../naming';
import type { ScaffoldPlan } from '../types';
import {
  cellExpression,
  defaultValueLiteral,
  entityNames,
  formFieldJsx,
  generateTypesFile,
  scalarColumns,
  zodSchemaLine,
  type TemplateOutput,
} from './shared';

function listColumns(plan: ScaffoldPlan) {
  const columns = scalarColumns(plan).filter((column) => column.inList);
  return columns.length > 0 ? columns : scalarColumns(plan).slice(0, 4);
}

function filterColumns(plan: ScaffoldPlan) {
  return scalarColumns(plan).filter(
    (column) => column.inFilters && column.type === 'enum'
  );
}

function buildFormSheet(plan: ScaffoldPlan): string {
  const names = entityNames(plan);
  const columns = scalarColumns(plan);
  const hasEnum = columns.some((column) => column.type === 'enum');
  const hasBoolean = columns.some((column) => column.type === 'boolean');
  const hasTextarea = columns.some((column) => column.type === 'text');

  const imports = [
    "'use client';",
    '',
    "import {\n  Form,\n  FormControl,\n  FormField,\n  FormItem,\n  FormLabel,\n  FormMessage,\n} from '@/components/ui/form';",
    "import { FormActions } from '@/components/ui/form-actions';",
    "import { Input } from '@/components/ui/input';",
    "import { ResizableSheetContent } from '@/components/ui/resizable-sheet-content';",
    "import { ScrollArea } from '@/components/ui/scroll-area';",
    ...(hasEnum
      ? [
          "import {\n  Select,\n  SelectContent,\n  SelectItem,\n  SelectTrigger,\n  SelectValue,\n} from '@/components/ui/select';",
        ]
      : []),
    "import {\n  Sheet,\n  SheetDescription,\n  SheetHeader,\n  SheetTitle,\n} from '@/components/ui/sheet';",
    ...(hasBoolean ? ["import { Switch } from '@/components/ui/switch';"] : []),
    ...(hasTextarea ? ["import { Textarea } from '@/components/ui/textarea';"] : []),
    "import { useFormDraft } from '@/hooks/use-form-draft';",
    "import { zodResolver } from '@hookform/resolvers/zod';",
    "import { useTranslations } from 'next-intl';",
    "import { useEffect } from 'react';",
    "import { useForm, useWatch } from 'react-hook-form';",
    "import { z } from 'zod';",
    `import type { ${names.pascal}, ${names.pascal}FormValues } from './${names.typesModule}';`,
  ];

  const defaults = columns
    .map((column) => `  ${column.name}: ${defaultValueLiteral(column)},`)
    .join('\n');

  const fromEntity = columns
    .map((column) => `        ${column.name}: item.${column.name},`)
    .join('\n');

  return [
    ...imports,
    '',
    `const DRAFT_STORAGE_KEY = '${plan.library}-${names.kebab}-form-draft';`,
    '',
    'const formSchema = z.object({',
    ...columns.map(zodSchemaLine),
    '});',
    '',
    `const emptyValues: ${names.pascal}FormValues = {`,
    defaults,
    '};',
    '',
    `type ${names.formSheetComponent}Props = {`,
    '  open: boolean;',
    '  onOpenChange: (open: boolean) => void;',
    `  item: ${names.pascal} | null;`,
    `  onSubmit: (values: ${names.pascal}FormValues) => Promise<void>;`,
    '  isLoading?: boolean;',
    '};',
    '',
    `export function ${names.formSheetComponent}({`,
    '  open,',
    '  onOpenChange,',
    '  item,',
    '  onSubmit,',
    '  isLoading = false,',
    `}: ${names.formSheetComponent}Props) {`,
    `  const t = useTranslations('${plan.library}.${toPascalCase(plan.entity)}Page');`,
    '',
    `  const form = useForm<${names.pascal}FormValues>({`,
    '    resolver: zodResolver(formSchema),',
    '    defaultValues: emptyValues,',
    '  });',
    '',
    '  const watchedValues = useWatch({ control: form.control });',
    '',
    '  const { clearDraft, loadDraft } = useFormDraft({',
    '    storageKey: DRAFT_STORAGE_KEY,',
    '    value: watchedValues,',
    '    hasData: Object.values(watchedValues ?? {}).some(',
    "      (value) => value !== null && value !== undefined && value !== ''",
    '    ),',
    '    enabled: open && !item,',
    '  });',
    '',
    '  useEffect(() => {',
    '    if (!open) {',
    '      return;',
    '    }',
    '',
    '    if (item) {',
    '      form.reset({',
    fromEntity,
    '      });',
    '      return;',
    '    }',
    '',
    '    const draft = loadDraft();',
    `    form.reset((draft?.payload as ${names.pascal}FormValues | undefined) ?? emptyValues);`,
    '  }, [form, item, loadDraft, open]);',
    '',
    `  const handleSubmit = async (values: ${names.pascal}FormValues) => {`,
    '    await onSubmit(values);',
    '    clearDraft();',
    '    onOpenChange(false);',
    '  };',
    '',
    '  return (',
    '    <Sheet open={open} onOpenChange={onOpenChange}>',
    `      <ResizableSheetContent sheetId="${plan.library}-${names.kebab}-form" className="flex flex-col gap-0 p-0">`,
    '        <SheetHeader className="border-b">',
    "          <SheetTitle>{item ? t('editTitle') : t('createTitle')}</SheetTitle>",
    "          <SheetDescription>{t('description')}</SheetDescription>",
    '        </SheetHeader>',
    '',
    '        <Form {...form}>',
    '          <form',
    '            onSubmit={form.handleSubmit(handleSubmit)}',
    '            className="flex min-h-0 flex-1 flex-col"',
    '          >',
    '            <ScrollArea className="min-h-0 flex-1">',
    '              <div className="space-y-4 p-4">',
    columns.map(formFieldJsx).join('\n\n'),
    '              </div>',
    '            </ScrollArea>',
    '',
    '            <FormActions',
    '              sheet',
    '              submitType="submit"',
    "              submitLabel={isLoading ? t('saving') : t('save')}",
    "              cancelLabel={t('cancel')}",
    '              submitDisabled={isLoading}',
    '              onCancel={() => {',
    '                clearDraft();',
    '                onOpenChange(false);',
    '              }}',
    '            />',
    '          </form>',
    '        </Form>',
    '      </ResizableSheetContent>',
    '    </Sheet>',
    '  );',
    '}',
    '',
  ].join('\n');
}

function buildPage(plan: ScaffoldPlan, withKpis: boolean): string {
  const names = entityNames(plan);
  const columns = listColumns(plan);
  const filters = filterColumns(plan);
  const enumColumn = scalarColumns(plan).find((column) => column.type === 'enum');

  const statsCards = withKpis
    ? [
        '  const statsCards = [',
        '    {',
        "      key: 'total',",
        "      title: t('statsTotal'),",
        '      value: stats.total,',
        '      icon: Layers,',
        "      accentClassName: 'from-slate-500/20 via-slate-400/10 to-transparent',",
        "      iconContainerClassName: 'bg-slate-100 text-slate-700',",
        '    },',
        ...(enumColumn?.enumValues ?? []).map((value) =>
          [
            '    {',
            `      key: '${value}',`,
            `      title: t('stats${toPascalCase(value)}'),`,
            `      value: stats.${value} ?? 0,`,
            '      icon: Layers,',
            "      accentClassName: 'from-blue-500/20 via-cyan-500/10 to-transparent',",
            "      iconContainerClassName: 'bg-blue-50 text-blue-600',",
            '    },',
          ].join('\n')
        ),
        '  ];',
        '',
      ]
    : [];

  const statsState = withKpis
    ? [
        '  const { data: stats = { total: 0 }, refetch: refetchStats } = useQuery<',
        '    Record<string, number>',
        '  >({',
        `    queryKey: ['${plan.library}-${names.kebab}-stats'],`,
        '    queryFn: async () => {',
        '      const response = await request<Record<string, number>>({',
        `        url: '${plan.apiBasePath}/stats',`,
        "        method: 'GET',",
        '      });',
        '',
        '      return response.data;',
        '    },',
        '    placeholderData: (previous) => previous ?? { total: 0 },',
        '  });',
        '',
      ]
    : [];

  const filterState = filters
    .map(
      (column) =>
        `  const [${column.name}Filter, set${toPascalCase(column.name)}Filter] = useState('all');`
    )
    .join('\n');

  const filterParams = filters
    .map((column) =>
      [
        `      if (${column.name}Filter !== 'all') {`,
        `        params.set('${column.name}', ${column.name}Filter);`,
        '      }',
      ].join('\n')
    )
    .join('\n');

  const filterControls = filters
    .map((column) =>
      [
        '    {',
        `      id: '${column.name}-filter',`,
        "      type: 'select',",
        `      value: ${column.name}Filter,`,
        '      onChange: (value: string) => {',
        `        set${toPascalCase(column.name)}Filter(value);`,
        '        setPage(1);',
        '      },',
        `      placeholder: t('column${toPascalCase(column.name)}'),`,
        '      options: [',
        `        { value: 'all', label: t('allOption') },`,
        ...(column.enumValues ?? []).map(
          (value) =>
            `        { value: '${value}', label: t('${column.name}_${value}') },`
        ),
        '      ],',
        '    },',
      ].join('\n')
    )
    .join('\n');

  const filterQueryKeys = filters.map((column) => `      ${column.name}Filter,`).join('\n');

  const tableHeaders = columns
    .map(
      (column) =>
        `                    <TableHead>{t('column${toPascalCase(column.name)}')}</TableHead>`
    )
    .join('\n');

  const tableCells = columns
    .map(
      (column) =>
        `                      <TableCell>{${cellExpression(column, 'item')}}</TableCell>`
    )
    .join('\n');

  const cardFields = columns
    .map((column) =>
      [
        '                      <div className="flex items-center justify-between gap-2">',
        `                        <span className="text-xs text-muted-foreground">{t('column${toPascalCase(
          column.name
        )}')}</span>`,
        `                        <span className="truncate text-sm">{${cellExpression(
          column,
          'item'
        )}}</span>`,
        '                      </div>',
      ].join('\n')
    )
    .join('\n');

  return [
    "'use client';",
    '',
    "import {\n  EmptyState,\n  Page,\n  PageHeader,\n  PaginationFooter,\n  SearchBar,\n  ViewModeToggle,\n  type SearchBarControl,\n} from '@/components/entity-list';",
    "import {\n  AlertDialog,\n  AlertDialogAction,\n  AlertDialogCancel,\n  AlertDialogContent,\n  AlertDialogDescription,\n  AlertDialogHeader,\n  AlertDialogTitle,\n} from '@/components/ui/alert-dialog';",
    "import { Button } from '@/components/ui/button';",
    "import { Card, CardContent } from '@/components/ui/card';",
    ...(withKpis ? ["import { KpiCardsGrid } from '@/components/ui/kpi-cards-grid';"] : []),
    "import {\n  Table,\n  TableBody,\n  TableCell,\n  TableHead,\n  TableHeader,\n  TableRow,\n} from '@/components/ui/table';",
    "import {\n  Tooltip,\n  TooltipContent,\n  TooltipTrigger,\n} from '@/components/ui/tooltip';",
    "import { useDebounce } from '@/hooks/use-debounce';",
    "import { usePersistedPageSize } from '@/hooks/use-persisted-page-size';",
    "import { usePersistedViewMode } from '@/hooks/use-persisted-view-mode';",
    "import { useApp, useQuery } from '@hed-hog/next-app-provider';",
    `import { ${withKpis ? 'Layers, ' : ''}Pencil, Plus, Trash2 } from 'lucide-react';`,
    "import { useTranslations } from 'next-intl';",
    "import { useMemo, useState } from 'react';",
    "import { toast } from 'sonner';",
    `import { ${names.formSheetComponent} } from './_components/${names.formSheetModule}';`,
    `import type {\n  ${names.pascal},\n  ${names.pascal}FormValues,\n  PaginatedResult,\n} from './_components/${names.typesModule}';`,
    '',
    'const PAGE_SIZE_OPTIONS = [12, 24, 48, 96] as const;',
    "const VIEW_MODES = ['list', 'cards'] as const;",
    '',
    `export default function ${names.pageComponent}() {`,
    `  const t = useTranslations('${plan.library}.${names.pascal}Page');`,
    '  const { request } = useApp();',
    '',
    '  const [searchInput, setSearchInput] = useState("");',
    '  const debouncedSearch = useDebounce(searchInput, 300);',
    '  const [page, setPage] = useState(1);',
    ...(filterState ? [filterState] : []),
    '  const [formOpen, setFormOpen] = useState(false);',
    `  const [itemToEdit, setItemToEdit] = useState<${names.pascal} | null>(null);`,
    `  const [itemToDelete, setItemToDelete] = useState<${names.pascal} | null>(null);`,
    '  const [isSubmitting, setIsSubmitting] = useState(false);',
    '',
    '  const [pageSize, setPageSize] = usePersistedPageSize({',
    `    storageKey: 'pagination:${plan.library}-${names.kebab}:pageSize',`,
    '    defaultValue: 12,',
    '    allowedValues: PAGE_SIZE_OPTIONS,',
    '  });',
    '',
    '  const [viewMode, setViewMode] = usePersistedViewMode({',
    `    storageKey: '${plan.library}-${names.kebab}-view-mode',`,
    "    defaultValue: 'list',",
    '    allowedValues: VIEW_MODES,',
    '  });',
    '',
    ...statsState,
    '  const {',
    '    data: paginate = {',
    '      data: [],',
    '      total: 0,',
    '      page: 1,',
    '      pageSize: 12,',
    '      lastPage: 1,',
    '      prev: null,',
    '      next: null,',
    '    },',
    '    isLoading,',
    '    refetch,',
    `  } = useQuery<PaginatedResult<${names.pascal}>>({`,
    '    queryKey: [',
    `      '${plan.library}-${names.kebab}',`,
    '      page,',
    '      pageSize,',
    '      debouncedSearch,',
    ...(filterQueryKeys ? [filterQueryKeys] : []),
    '    ],',
    '    queryFn: async () => {',
    '      const params = new URLSearchParams();',
    "      params.set('page', String(page));",
    "      params.set('pageSize', String(pageSize));",
    '',
    '      if (debouncedSearch) {',
    "        params.set('search', debouncedSearch);",
    '      }',
    '',
    ...(filterParams ? [filterParams] : []),
    `      const response = await request<PaginatedResult<${names.pascal}>>({`,
    `        url: \`${plan.apiBasePath}?\${params.toString()}\`,`,
    "        method: 'GET',",
    '      });',
    '',
    '      return response.data;',
    '    },',
    '    placeholderData: (previous) =>',
    '      previous ?? {',
    '        data: [],',
    '        total: 0,',
    '        page: 1,',
    '        pageSize: 12,',
    '        lastPage: 1,',
    '        prev: null,',
    '        next: null,',
    '      },',
    '  });',
    '',
    '  const totalPages = Math.max(1, paginate.lastPage ?? 1);',
    '  // Página exibida é derivada no render: busca e filtros já voltam para a',
    '  // primeira página, e o clamp evita um efeito que dispararia render extra.',
    '  const safePage = Math.min(page, totalPages);',
    '',
    ...statsCards,
    '  const searchControls: SearchBarControl[] = [',
    ...(filterControls ? [filterControls] : []),
    '  ];',
    '',
    `  const handleSubmit = async (values: ${names.pascal}FormValues) => {`,
    '    try {',
    '      setIsSubmitting(true);',
    '',
    '      if (itemToEdit) {',
    '        await request({',
    `          url: \`${plan.apiBasePath}/\${itemToEdit.id}\`,`,
    "          method: 'PATCH',",
    '          data: values,',
    '        });',
    "        toast.success(t('editSuccess'));",
    '      } else {',
    '        await request({',
    `          url: '${plan.apiBasePath}',`,
    "          method: 'POST',",
    '          data: values,',
    '        });',
    "        toast.success(t('createSuccess'));",
    '      }',
    '',
    ...(withKpis
      ? ['      await Promise.all([refetch(), refetchStats()]);']
      : ['      await refetch();']),
    '    } catch {',
    "      toast.error(t('saveError'));",
    '    } finally {',
    '      setIsSubmitting(false);',
    '    }',
    '  };',
    '',
    '  const handleDelete = async () => {',
    '    if (!itemToDelete) {',
    '      return;',
    '    }',
    '',
    '    try {',
    '      await request({',
    `        url: \`${plan.apiBasePath}/\${itemToDelete.id}\`,`,
    "        method: 'DELETE',",
    '      });',
    '',
    "      toast.success(t('deleteSuccess'));",
    '      setItemToDelete(null);',
    ...(withKpis
      ? ['      await Promise.all([refetch(), refetchStats()]);']
      : ['      await refetch();']),
    '    } catch {',
    "      toast.error(t('deleteError'));",
    '    }',
    '  };',
    '',
    '  const items = useMemo(() => paginate.data, [paginate.data]);',
    '',
    '  return (',
    '    <Page>',
    '      <PageHeader',
    '        breadcrumbs={[',
    "          { label: t('breadcrumbHome'), href: '/' },",
    "          { label: t('title') },",
    '        ]}',
    "        title={t('title')}",
    "        description={t('description')}",
    '        actions={[',
    '          {',
    "            label: t('newItem'),",
    '            onClick: () => {',
    '              setItemToEdit(null);',
    '              setFormOpen(true);',
    '            },',
    '            icon: <Plus className="h-4 w-4" />,',
    '          },',
    '        ]}',
    '      />',
    '',
    ...(withKpis ? ['      <KpiCardsGrid items={statsCards} />', ''] : []),
    '      <div className="flex flex-col gap-4 xl:flex-row xl:items-center">',
    '        <div className="flex-1">',
    '          <SearchBar',
    '            searchQuery={searchInput}',
    '            onSearchChange={(value) => {',
    '              setSearchInput(value);',
    '              setPage(1);',
    '            }}',
    '            onSearch={() => setPage(1)}',
    "            placeholder={t('searchPlaceholder')}",
    '            controls={searchControls}',
    '          />',
    '        </div>',
    '',
    '        <div className="flex items-center justify-between gap-3 sm:justify-start xl:justify-end">',
    '          <span className="text-xs font-medium text-muted-foreground">',
    "            {t('viewMode')}",
    '          </span>',
    '          <ViewModeToggle',
    '            viewMode={viewMode}',
    '            onViewModeChange={setViewMode}',
    "            listLabel={t('viewModeTable')}",
    "            cardsLabel={t('viewModeCards')}",
    '          />',
    '        </div>',
    '      </div>',
    '',
    '      {!isLoading && items.length === 0 ? (',
    '        <EmptyState',
    '          icon={<Plus className="h-12 w-12" />}',
    "          title={t('emptyStateTitle')}",
    "          description={t('emptyStateDescription')}",
    "          actionLabel={t('newItem')}",
    '          onAction={() => {',
    '            setItemToEdit(null);',
    '            setFormOpen(true);',
    '          }}',
    '        />',
    '      ) : (',
    '        <>',
    "          {viewMode === 'list' ? (",
    '            <div className="overflow-x-auto">',
    '              <Table>',
    '                <TableHeader>',
    '                  <TableRow>',
    tableHeaders,
    "                    <TableHead className=\"text-right\">{t('columnActions')}</TableHead>",
    '                  </TableRow>',
    '                </TableHeader>',
    '                <TableBody>',
    '                  {items.map((item) => (',
    '                    <TableRow',
    '                      key={item.id}',
    '                      className="cursor-pointer"',
    '                      onDoubleClick={() => {',
    '                        setItemToEdit(item);',
    '                        setFormOpen(true);',
    '                      }}',
    '                    >',
    tableCells,
    '                      <TableCell>',
    '                        <div className="flex items-center justify-end gap-1">',
    '                          <Tooltip>',
    '                            <TooltipTrigger asChild>',
    '                              <Button',
    '                                variant="ghost"',
    '                                size="icon"',
    '                                className="h-8 w-8"',
    '                                onClick={() => {',
    '                                  setItemToEdit(item);',
    '                                  setFormOpen(true);',
    '                                }}',
    '                              >',
    '                                <Pencil className="h-4 w-4" />',
    '                              </Button>',
    '                            </TooltipTrigger>',
    "                            <TooltipContent>{t('edit')}</TooltipContent>",
    '                          </Tooltip>',
    '                          <Tooltip>',
    '                            <TooltipTrigger asChild>',
    '                              <Button',
    '                                variant="ghost"',
    '                                size="icon"',
    '                                className="h-8 w-8 text-red-600"',
    '                                onClick={() => setItemToDelete(item)}',
    '                              >',
    '                                <Trash2 className="h-4 w-4" />',
    '                              </Button>',
    '                            </TooltipTrigger>',
    "                            <TooltipContent>{t('delete')}</TooltipContent>",
    '                          </Tooltip>',
    '                        </div>',
    '                      </TableCell>',
    '                    </TableRow>',
    '                  ))}',
    '                </TableBody>',
    '              </Table>',
    '            </div>',
    '          ) : (',
    '            <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">',
    '              {items.map((item) => (',
    '                <Card',
    '                  key={item.id}',
    '                  className="cursor-pointer border-border/70 py-0 transition-colors hover:border-border hover:shadow-md"',
    '                  onClick={() => {',
    '                    setItemToEdit(item);',
    '                    setFormOpen(true);',
    '                  }}',
    '                >',
    '                  <CardContent className="space-y-2 p-4">',
    cardFields,
    '                  </CardContent>',
    '                </Card>',
    '              ))}',
    '            </div>',
    '          )}',
    '',
    '          <PaginationFooter',
    '            currentPage={safePage}',
    '            pageSize={pageSize}',
    '            totalItems={paginate.total}',
    '            onPageChange={setPage}',
    '            onPageSizeChange={(nextPageSize) => {',
    '              setPageSize(nextPageSize);',
    '              setPage(1);',
    '            }}',
    '            pageSizeOptions={PAGE_SIZE_OPTIONS}',
    '          />',
    '        </>',
    '      )}',
    '',
    `      <${names.formSheetComponent}`,
    '        open={formOpen}',
    '        onOpenChange={setFormOpen}',
    '        item={itemToEdit}',
    '        onSubmit={handleSubmit}',
    '        isLoading={isSubmitting}',
    '      />',
    '',
    '      <AlertDialog',
    '        open={Boolean(itemToDelete)}',
    '        onOpenChange={(open) => {',
    '          if (!open) {',
    '            setItemToDelete(null);',
    '          }',
    '        }}',
    '      >',
    '        <AlertDialogContent>',
    '          <AlertDialogHeader>',
    "            <AlertDialogTitle>{t('deleteTitle')}</AlertDialogTitle>",
    '            <AlertDialogDescription>',
    "              {t('deleteDescription')}",
    '            </AlertDialogDescription>',
    '          </AlertDialogHeader>',
    '          <div className="flex justify-end gap-3">',
    "            <AlertDialogCancel>{t('cancel')}</AlertDialogCancel>",
    '            <AlertDialogAction',
    '              onClick={handleDelete}',
    '              className="bg-red-600 hover:bg-red-700"',
    '            >',
    "              {t('delete')}",
    '            </AlertDialogAction>',
    '          </div>',
    '        </AlertDialogContent>',
    '      </AlertDialog>',
    '    </Page>',
    '  );',
    '}',
    '',
  ].join('\n');
}

export function renderListTemplate(
  plan: ScaffoldPlan,
  withKpis: boolean
): TemplateOutput {
  const names = entityNames(plan);

  return {
    page: buildPage(plan, withKpis),
    components: [
      {
        relativePath: `_components/${names.typesModule}.ts`,
        contents: generateTypesFile(plan),
      },
      {
        relativePath: `_components/${names.formSheetModule}.tsx`,
        contents: buildFormSheet(plan),
      },
    ],
  };
}
